ARG MINICONDA_VERSION=3
FROM godatadriven/miniconda:${MINICONDA_VERSION}

LABEL org.label-schema.name="Python $MINICONDA_VERSION OnBuild CONDA" \
      org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.version=$MINICONDA_VERSION

ONBUILD ADD environment.yml packages.txt* build.sh* /dependencies/
ONBUILD RUN set -x\
            && apt-get update \
            && apt-get install -y gcc g++\
            && if [ -f /dependencies/packages.txt ]; then\
                apt-get install -y $(awk '/^\s*[^#]/' /dependencies/packages.txt | sed 's/\r//g');\
               fi\
            && conda env update --file /dependencies/environment.yml -n root \
            && if [ -f /dependencies/build.sh ]; then\
                bash /dependencies/build.sh;\
               fi\
            && conda clean -tipsy \
            && apt-get purge -y --auto-remove gcc g++\
            && apt-get clean

ENV PYTHONUNBUFFERED true
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /app
ENTRYPOINT ["python"]
CMD ["/app/main.py"]