#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.
IMAGE_REPO=${IMAGE_NAME%:*}
IMAGE_TAG=${IMAGE_NAME#*:}

DEP_TYPE=${IMAGE_TAG%-*}
PYTHON_TAG=${IMAGE_TAG#*-}
PYTHON_VERSION=${PYTHON_TAG:6}
DOCKERFILE="Dockerfile_${DEP_TYPE}"

# Trigger build
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg MINICONDA_VERSION=$PYTHON_VERSION \
             -t $IMAGE_NAME -f $DOCKERFILE .