#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.
IMAGE_REPO=${IMAGE_NAME%:*}
IMAGE_TAG=${IMAGE_NAME#*:}

# Retag to latest
if [ "$IMAGE_TAG" = "pip-python3.6" ]; then
    docker tag $IMAGE_NAME ${IMAGE_REPO}:latest
    docker push ${IMAGE_REPO}:latest
    
    docker tag $IMAGE_NAME ${IMAGE_REPO}:pip
    docker push ${IMAGE_REPO}:pip
fi

# Retag to conda
if [ "$IMAGE_TAG" = "conda-python3.6" ]; then
    docker tag $IMAGE_NAME ${IMAGE_REPO}:conda
    docker push ${IMAGE_REPO}:conda
fi